#---------------------------------------------------------------------------------------------
# 
# Name: query_gbif.R
# Purpose: 
# Author: Christopher Tracey
# Created: 2016-08-11
# Updated: 2016-08-17
#
# Updates:
# insert date and info
# * 2016-08-17 - got the code to remove NULL values from the keys to work; 
#                added the complete list of SGCN to load from a text file;
#                figured out how to remove records where no occurences we found;
#                make a shapefile of the results  
#
# To Do List/Future Ideas:
# * check projection
# * wkt integration
# * filter the occ_search results on potential data flags -- looks like its pulling 
#   the coordinates from iNat that are obscured.  
# * might be a good idea to create seperate reports with obscured records

#-------

library('rgbif')
library('plyr')
library('maps')
library('maptools')

# genetates a species list of SNAMEs for querying gbif
splist <- readLines("data_SGCNlist.csv") # alternatively, can go from here: splist <- c("Piranga olivacea","Quercus alba","Ambystoma jeffersonianum","Aneides aeneus","Clonophis kirtlandii","Kinosternon subrubrum","Accipiter gentilis","Glyptemys insculpta","madeuptestname")
# gets the  keys for each species name, based on GBIF
keys <- sapply(splist, function(x) name_backbone(name=x)$speciesKey, USE.NAMES=FALSE)
# gets rid of any null values generated by name_backbone in the case of unmatchable species names
keys=keys[-(which(sapply(keys,is.null),arr.ind=TRUE))]
#note: the above lnes seems to break, if there is only one item in the list... use for multiple species!
#searches for occurrences
dat <- occ_search(
                  taxonKey=keys, 
                  limit=30000, 
                  return='data', 
                  hasCoordinate=TRUE,
                  geometry=c(-80.5195, 39.7199, -74.6896, 42.2695),
                  year='1990,2016',
                  fields=c('name','key','decimalLatitude','decimalLongitude','country','basisOfRecord','coordinateAccuracy','year','month','day')
                 )
# deletes the items from the list where no occurences were found.
dat <-  dat[dat!="no data found, try a different search"]
# turns the list to a data frame
datdf <- ldply(dat)

# Write data frame to csv
write.csv(datdf,file = "GBIF_Export_8252016.csv")

# make a map, doesn't work with a lot of species
#gbifmap(datdf, mapdatabase="state", region="pennsylvania")

#create a shapefile
# based on http://neondataskills.org/R/csv-to-shapefile-R/
library(rgdal)  # for vector work; sp package should always load with rgdal. 
library (raster)   # for metadata/attributes- vectors or rasters
# note that the easting and northing columns are in columns 4 and 5
SGCNgbif <- SpatialPointsDataFrame(datdf[,5:6],datdf,,proj4string <- CRS("+init=epsg:4326"))   # assign a CRS  ,proj4string = utm18nCR  #https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf; the two commas in a row are important due to the slots feature
plot(SGCNgbif,main="Map of SGCN Locations")
# write a shapefile
writeOGR(SGCNgbif, getwd(),"SGCN_FromGBIFb", driver="ESRI Shapefile")


